import bisect
import random

WEBSITES: list[tuple[str, str]] = [
    # --- Top 50: Major sites ---
    ("www.google.com", "Google"),
    ("www.youtube.com", "YouTube"),
    ("www.facebook.com", "Facebook"),
    ("www.amazon.com", "Amazon"),
    ("www.netflix.com", "Netflix"),
    ("www.tiktok.com", "TikTok"),
    ("www.instagram.com", "Instagram"),
    ("x.com", "X"),
    ("www.reddit.com", "Reddit"),
    ("en.wikipedia.org", "Wikipedia"),
    ("www.linkedin.com", "LinkedIn"),
    ("web.whatsapp.com", "WhatsApp"),
    ("www.bing.com", "Bing"),
    ("www.yahoo.com", "Yahoo"),
    ("www.twitch.tv", "Twitch"),
    ("www.pinterest.com", "Pinterest"),
    ("www.snapchat.com", "Snapchat"),
    ("discord.com", "Discord"),
    ("web.telegram.org", "Telegram"),
    ("open.spotify.com", "Spotify"),
    ("www.apple.com", "Apple"),
    ("www.microsoft.com", "Microsoft"),
    ("github.com", "GitHub"),
    ("stackoverflow.com", "Stack Overflow"),
    ("www.cnn.com", "CNN"),
    ("www.bbc.com", "BBC"),
    ("www.espn.com", "ESPN"),
    ("www.nytimes.com", "New York Times"),
    ("www.washingtonpost.com", "Washington Post"),
    ("www.forbes.com", "Forbes"),
    ("www.bloomberg.com", "Bloomberg"),
    ("weather.com", "The Weather Channel"),
    ("www.zillow.com", "Zillow"),
    ("www.realtor.com", "Realtor.com"),
    ("www.airbnb.com", "Airbnb"),
    ("www.uber.com", "Uber"),
    ("www.doordash.com", "DoorDash"),
    ("www.grubhub.com", "Grubhub"),
    ("venmo.com", "Venmo"),
    ("www.paypal.com", "PayPal"),
    ("www.chase.com", "Chase"),
    ("www.bankofamerica.com", "Bank of America"),
    ("www.wellsfargo.com", "Wells Fargo"),
    ("www.fidelity.com", "Fidelity"),
    ("www.schwab.com", "Charles Schwab"),
    ("robinhood.com", "Robinhood"),
    ("www.coinbase.com", "Coinbase"),
    ("www.webmd.com", "WebMD"),
    ("www.mayoclinic.org", "Mayo Clinic"),
    ("www.healthline.com", "Healthline"),
    # --- Next 100: Well-known sites across categories ---
    # News
    ("www.reuters.com", "Reuters"),
    ("apnews.com", "AP News"),
    ("www.usatoday.com", "USA Today"),
    ("www.theguardian.com", "The Guardian"),
    ("www.foxnews.com", "Fox News"),
    ("www.nbcnews.com", "NBC News"),
    ("abcnews.go.com", "ABC News"),
    ("www.cbsnews.com", "CBS News"),
    ("www.npr.org", "NPR"),
    ("www.politico.com", "Politico"),
    ("www.huffpost.com", "HuffPost"),
    ("www.axios.com", "Axios"),
    ("www.theatlantic.com", "The Atlantic"),
    ("www.wsj.com", "Wall Street Journal"),
    ("www.economist.com", "The Economist"),
    # Shopping
    ("www.walmart.com", "Walmart"),
    ("www.target.com", "Target"),
    ("www.ebay.com", "eBay"),
    ("www.etsy.com", "Etsy"),
    ("www.bestbuy.com", "Best Buy"),
    ("www.costco.com", "Costco"),
    ("www.homedepot.com", "Home Depot"),
    ("www.lowes.com", "Lowes"),
    ("www.wayfair.com", "Wayfair"),
    ("www.macys.com", "Macys"),
    ("www.nordstrom.com", "Nordstrom"),
    ("www.zappos.com", "Zappos"),
    ("www.shein.com", "Shein"),
    ("www.ikea.com", "IKEA"),
    ("www.aliexpress.com", "AliExpress"),
    # Social / Tech
    ("www.tumblr.com", "Tumblr"),
    ("www.quora.com", "Quora"),
    ("news.ycombinator.com", "Hacker News"),
    ("www.flickr.com", "Flickr"),
    ("www.meetup.com", "Meetup"),
    ("www.goodreads.com", "Goodreads"),
    ("medium.com", "Medium"),
    ("substack.com", "Substack"),
    ("www.deviantart.com", "DeviantArt"),
    ("gitlab.com", "GitLab"),
    ("bitbucket.org", "Bitbucket"),
    ("www.notion.so", "Notion"),
    ("www.figma.com", "Figma"),
    ("www.canva.com", "Canva"),
    ("www.dropbox.com", "Dropbox"),
    # Education
    ("www.khanacademy.org", "Khan Academy"),
    ("www.coursera.org", "Coursera"),
    ("www.udemy.com", "Udemy"),
    ("www.edx.org", "edX"),
    ("www.duolingo.com", "Duolingo"),
    ("www.chegg.com", "Chegg"),
    ("scholar.google.com", "Google Scholar"),
    ("www.britannica.com", "Britannica"),
    # Entertainment
    ("www.hulu.com", "Hulu"),
    ("www.disneyplus.com", "Disney+"),
    ("www.hbomax.com", "HBO Max"),
    ("www.peacocktv.com", "Peacock"),
    ("www.paramountplus.com", "Paramount+"),
    ("www.crunchyroll.com", "Crunchyroll"),
    ("www.imdb.com", "IMDb"),
    ("www.rottentomatoes.com", "Rotten Tomatoes"),
    ("www.soundcloud.com", "SoundCloud"),
    ("www.pandora.com", "Pandora"),
    # Finance
    ("www.nerdwallet.com", "NerdWallet"),
    ("www.creditkarma.com", "Credit Karma"),
    ("www.mint.com", "Mint"),
    ("finance.yahoo.com", "Yahoo Finance"),
    ("www.marketwatch.com", "MarketWatch"),
    ("www.investopedia.com", "Investopedia"),
    ("www.bankrate.com", "Bankrate"),
    # Health
    ("www.nih.gov", "NIH"),
    ("www.cdc.gov", "CDC"),
    ("www.medlineplus.gov", "MedlinePlus"),
    ("www.drugs.com", "Drugs.com"),
    ("www.everydayhealth.com", "Everyday Health"),
    # Travel
    ("www.booking.com", "Booking.com"),
    ("www.expedia.com", "Expedia"),
    ("www.tripadvisor.com", "TripAdvisor"),
    ("www.kayak.com", "Kayak"),
    ("www.hotels.com", "Hotels.com"),
    ("www.southwest.com", "Southwest Airlines"),
    ("www.united.com", "United Airlines"),
    ("www.delta.com", "Delta Airlines"),
    # Food
    ("www.allrecipes.com", "Allrecipes"),
    ("www.foodnetwork.com", "Food Network"),
    ("www.epicurious.com", "Epicurious"),
    ("www.seriouseats.com", "Serious Eats"),
    # Sports
    ("www.nfl.com", "NFL"),
    ("www.nba.com", "NBA"),
    ("www.mlb.com", "MLB"),
    ("bleacherreport.com", "Bleacher Report"),
    ("www.cbssports.com", "CBS Sports"),
    # Gaming
    ("store.steampowered.com", "Steam"),
    ("www.ign.com", "IGN"),
    ("www.gamespot.com", "GameSpot"),
    ("www.epicgames.com", "Epic Games"),
    ("www.roblox.com", "Roblox"),
    # --- Remaining ~350: Long-tail sites ---
    # Regional / local news
    ("www.chicagotribune.com", "Chicago Tribune"),
    ("www.latimes.com", "Los Angeles Times"),
    ("www.sfchronicle.com", "San Francisco Chronicle"),
    ("www.dallasnews.com", "Dallas Morning News"),
    ("www.seattletimes.com", "Seattle Times"),
    ("www.denverpost.com", "Denver Post"),
    ("www.miamiherald.com", "Miami Herald"),
    ("www.bostonglobe.com", "Boston Globe"),
    ("www.ajc.com", "Atlanta Journal-Constitution"),
    ("www.startribune.com", "Star Tribune"),
    ("www.oregonlive.com", "The Oregonian"),
    ("www.freep.com", "Detroit Free Press"),
    ("www.azcentral.com", "Arizona Republic"),
    ("www.sacbee.com", "Sacramento Bee"),
    ("www.tampabay.com", "Tampa Bay Times"),
    ("www.sun-sentinel.com", "South Florida Sun-Sentinel"),
    ("www.stltoday.com", "St. Louis Post-Dispatch"),
    ("www.kansascity.com", "Kansas City Star"),
    ("www.indystar.com", "Indianapolis Star"),
    ("www.jsonline.com", "Milwaukee Journal Sentinel"),
    ("www.dispatch.com", "Columbus Dispatch"),
    ("www.tennessean.com", "The Tennessean"),
    ("www.courier-journal.com", "Courier Journal"),
    ("www.desmoinesregister.com", "Des Moines Register"),
    ("www.oklahoman.com", "The Oklahoman"),
    # Niche tech / dev
    ("dev.to", "DEV Community"),
    ("lobste.rs", "Lobsters"),
    ("www.infoq.com", "InfoQ"),
    ("dzone.com", "DZone"),
    ("www.smashingmagazine.com", "Smashing Magazine"),
    ("css-tricks.com", "CSS-Tricks"),
    ("www.freecodecamp.org", "freeCodeCamp"),
    ("www.codecademy.com", "Codecademy"),
    ("realpython.com", "Real Python"),
    ("go.dev", "Go Dev"),
    ("doc.rust-lang.org", "Rust Docs"),
    ("kotlinlang.org", "Kotlin"),
    ("www.typescriptlang.org", "TypeScript"),
    ("vuejs.org", "Vue.js"),
    ("angular.io", "Angular"),
    ("svelte.dev", "Svelte"),
    ("nextjs.org", "Next.js"),
    ("tailwindcss.com", "Tailwind CSS"),
    ("www.terraform.io", "Terraform"),
    ("www.ansible.com", "Ansible"),
    ("kubernetes.io", "Kubernetes"),
    ("www.docker.com", "Docker"),
    ("grafana.com", "Grafana"),
    ("prometheus.io", "Prometheus"),
    ("www.elastic.co", "Elastic"),
    ("www.datadoghq.com", "Datadog"),
    # Specialty e-commerce / niche retail
    ("www.chewy.com", "Chewy"),
    ("www.petco.com", "Petco"),
    ("www.petsmart.com", "PetSmart"),
    ("www.rei.com", "REI"),
    ("www.backcountry.com", "Backcountry"),
    ("www.moosejaw.com", "Moosejaw"),
    ("www.dickssportinggoods.com", "Dicks Sporting Goods"),
    ("www.academy.com", "Academy Sports"),
    ("www.bathandbodyworks.com", "Bath and Body Works"),
    ("www.sephora.com", "Sephora"),
    ("www.ulta.com", "Ulta Beauty"),
    ("www.glossier.com", "Glossier"),
    ("www.warbyparker.com", "Warby Parker"),
    ("www.casper.com", "Casper"),
    ("www.allbirds.com", "Allbirds"),
    ("www.bombas.com", "Bombas"),
    ("www.everlane.com", "Everlane"),
    ("www.uniqlo.com", "Uniqlo"),
    ("www.asos.com", "ASOS"),
    ("www.urbanoutfitters.com", "Urban Outfitters"),
    ("www.anthropologie.com", "Anthropologie"),
    ("www.freepeople.com", "Free People"),
    ("www.lululemon.com", "Lululemon"),
    ("www.nike.com", "Nike"),
    ("www.adidas.com", "Adidas"),
    ("www.underarmour.com", "Under Armour"),
    ("www.newbalance.com", "New Balance"),
    ("www.patagonia.com", "Patagonia"),
    ("www.northface.com", "The North Face"),
    ("www.columbia.com", "Columbia Sportswear"),
    # Forums / communities
    ("forums.whirlpool.net.au", "Whirlpool Forums"),
    ("www.avsforum.com", "AVS Forum"),
    ("www.head-fi.org", "Head-Fi"),
    ("www.audiosciencereview.com", "Audio Science Review"),
    ("www.overclock.net", "Overclock.net"),
    ("linustechtips.com", "Linus Tech Tips"),
    ("forum.xda-developers.com", "XDA Developers"),
    ("www.spiceworks.com", "Spiceworks"),
    ("community.cloudflare.com", "Cloudflare Community"),
    ("discuss.hashicorp.com", "HashiCorp Discuss"),
    ("www.bogleheads.org", "Bogleheads"),
    ("www.biggerpockets.com", "BiggerPockets"),
    ("www.fishlore.com", "Fishlore"),
    ("www.gardenweb.com", "GardenWeb"),
    ("www.woodworkingtalk.com", "Woodworking Talk"),
    # Food / cooking blogs
    ("www.budgetbytes.com", "Budget Bytes"),
    ("www.skinnytaste.com", "Skinnytaste"),
    ("pinchofyum.com", "Pinch of Yum"),
    ("www.halfbakedharvest.com", "Half Baked Harvest"),
    ("minimalistbaker.com", "Minimalist Baker"),
    ("cookieandkate.com", "Cookie and Kate"),
    ("www.loveandlemons.com", "Love and Lemons"),
    ("www.bonappetit.com", "Bon Appetit"),
    ("smittenkitchen.com", "Smitten Kitchen"),
    ("thepioneerwoman.com", "The Pioneer Woman"),
    ("www.simplyrecipes.com", "Simply Recipes"),
    ("www.kingarthurbaking.com", "King Arthur Baking"),
    ("sallysbakingaddiction.com", "Sallys Baking Addiction"),
    ("www.onceuponachef.com", "Once Upon a Chef"),
    ("www.recipetineats.com", "RecipeTin Eats"),
    # Health / fitness / wellness
    ("www.myfitnesspal.com", "MyFitnessPal"),
    ("www.strava.com", "Strava"),
    ("www.fitbit.com", "Fitbit"),
    ("www.bodybuilding.com", "Bodybuilding.com"),
    ("www.menshealth.com", "Mens Health"),
    ("www.womenshealthmag.com", "Womens Health"),
    ("www.runnersworld.com", "Runners World"),
    ("www.yogajournal.com", "Yoga Journal"),
    ("www.mindbodygreen.com", "MindBodyGreen"),
    ("www.psychologytoday.com", "Psychology Today"),
    ("www.calm.com", "Calm"),
    ("www.headspace.com", "Headspace"),
    # Personal finance / niche finance
    ("www.mrmoneymustache.com", "Mr. Money Mustache"),
    ("www.financialsamurai.com", "Financial Samurai"),
    ("www.thepennyhoarder.com", "The Penny Hoarder"),
    ("www.fool.com", "Motley Fool"),
    ("seekingalpha.com", "Seeking Alpha"),
    ("www.thebalancemoney.com", "The Balance"),
    ("www.daveramsey.com", "Dave Ramsey"),
    # Parenting / family
    ("www.whattoexpect.com", "What to Expect"),
    ("www.babycenter.com", "BabyCenter"),
    ("www.parents.com", "Parents Magazine"),
    ("www.scarymommy.com", "Scary Mommy"),
    ("www.fatherly.com", "Fatherly"),
    # Automotive
    ("www.caranddriver.com", "Car and Driver"),
    ("www.motortrend.com", "MotorTrend"),
    ("www.edmunds.com", "Edmunds"),
    ("www.kbb.com", "Kelley Blue Book"),
    ("www.autotrader.com", "AutoTrader"),
    ("www.carvana.com", "Carvana"),
    ("www.carmax.com", "CarMax"),
    ("jalopnik.com", "Jalopnik"),
    ("www.thedrive.com", "The Drive"),
    # Home / DIY
    ("www.apartmenttherapy.com", "Apartment Therapy"),
    ("www.thisoldhouse.com", "This Old House"),
    ("www.bobvila.com", "Bob Vila"),
    ("www.familyhandyman.com", "Family Handyman"),
    ("www.bhg.com", "Better Homes and Gardens"),
    ("www.hgtv.com", "HGTV"),
    ("www.architecturaldigest.com", "Architectural Digest"),
    ("www.dwell.com", "Dwell"),
    # Education / reference
    ("www.wolfram.com", "Wolfram"),
    ("www.mathway.com", "Mathway"),
    ("www.sparknotes.com", "SparkNotes"),
    ("www.cliffsnotes.com", "CliffsNotes"),
    ("www.grammarly.com", "Grammarly"),
    ("www.merriam-webster.com", "Merriam-Webster"),
    ("www.thesaurus.com", "Thesaurus.com"),
    ("www.dictionary.com", "Dictionary.com"),
    # Photography / creative
    ("500px.com", "500px"),
    ("unsplash.com", "Unsplash"),
    ("www.shutterstock.com", "Shutterstock"),
    ("www.gettyimages.com", "Getty Images"),
    ("www.behance.net", "Behance"),
    ("dribbble.com", "Dribbble"),
    ("www.artstation.com", "ArtStation"),
    # Music / audio
    ("bandcamp.com", "Bandcamp"),
    ("pitchfork.com", "Pitchfork"),
    ("www.rollingstone.com", "Rolling Stone"),
    ("www.stereogum.com", "Stereogum"),
    ("www.billboard.com", "Billboard"),
    # Science / academic
    ("arxiv.org", "arXiv"),
    ("www.nature.com", "Nature"),
    ("www.sciencedirect.com", "ScienceDirect"),
    ("www.researchgate.net", "ResearchGate"),
    ("pubmed.ncbi.nlm.nih.gov", "PubMed"),
    ("www.sciencemag.org", "Science Magazine"),
    ("www.newscientist.com", "New Scientist"),
    ("www.space.com", "Space.com"),
    ("www.livescience.com", "Live Science"),
    # Small / plausible fictional long-tail sites
    ("www.midwestgardenguide.com", "Midwest Garden Guide"),
    ("www.trailrunnerweekly.com", "Trail Runner Weekly"),
    ("www.tinyhouseliving.net", "Tiny House Living"),
    ("www.backyardchickenkeeper.com", "Backyard Chicken Keeper"),
    ("www.sourdoughsimplified.com", "Sourdough Simplified"),
    ("www.thefrugalprepper.com", "The Frugal Prepper"),
    ("www.vintagetoolcollector.com", "Vintage Tool Collector"),
    ("www.weekendvanlife.com", "Weekend Van Life"),
    ("www.coastalfishingguide.com", "Coastal Fishing Guide"),
    ("www.homeroastcoffee.com", "Home Roast Coffee"),
    ("www.retrocomputingforum.org", "Retro Computing Forum"),
    ("www.indieboardgamer.com", "Indie Board Gamer"),
    ("www.smallbatchbrewing.com", "Small Batch Brewing"),
    ("www.garagesalefinder.net", "Garage Sale Finder"),
    ("www.suburbanhomesteader.com", "Suburban Homesteader"),
    ("www.quiltersconnection.com", "Quilters Connection"),
    ("www.budgetbackpacker.net", "Budget Backpacker"),
    ("www.lakecabinliving.com", "Lake Cabin Living"),
    ("www.mountainbikemechanic.com", "Mountain Bike Mechanic"),
    ("www.diysolarpanels.org", "DIY Solar Panels"),
    ("www.nightskywatcher.com", "Night Sky Watcher"),
    ("www.paddleboarddaily.com", "Paddleboard Daily"),
    ("www.herbalgardentips.com", "Herbal Garden Tips"),
    ("www.thriftflipguide.com", "Thrift Flip Guide"),
    ("www.campervanconversions.net", "Camper Van Conversions"),
    ("www.urbanforaging.org", "Urban Foraging"),
    ("www.bonsaitree.guide", "Bonsai Tree Guide"),
    ("www.leatherworkingbasics.com", "Leatherworking Basics"),
    ("www.freshwaterfishfinder.com", "Freshwater Fish Finder"),
    ("www.vinylcollectorhub.com", "Vinyl Collector Hub"),
    ("www.minimalistpacking.com", "Minimalist Packing"),
    ("www.rockclimbinglog.com", "Rock Climbing Log"),
    ("www.fermenteverything.com", "Ferment Everything"),
    ("www.thecrochetcorner.com", "The Crochet Corner"),
    ("www.amateurradioweekly.com", "Amateur Radio Weekly"),
    ("www.candlemakingcraft.com", "Candle Making Craft"),
    ("www.flatwaterpaddler.com", "Flatwater Paddler"),
    ("www.droneflyer.net", "Drone Flyer"),
    ("www.troutstreams.org", "Trout Streams"),
    ("www.homecheesemaking.com", "Home Cheese Making"),
    ("www.backcountryhunter.net", "Backcountry Hunter"),
    ("www.seedstarting101.com", "Seed Starting 101"),
    ("www.weekendhiker.blog", "Weekend Hiker Blog"),
    ("www.oldhouserenovation.com", "Old House Renovation"),
    ("www.aquaponicsathome.com", "Aquaponics at Home"),
    ("www.crossstitchpatterns.net", "Cross Stitch Patterns"),
    ("www.metaldetectingfinds.com", "Metal Detecting Finds"),
    ("www.beekeepersjournal.org", "Beekeepers Journal"),
    ("www.3dprintprojects.com", "3D Print Projects"),
    ("www.kayakfisherman.net", "Kayak Fisherman"),
    ("www.composting101.com", "Composting 101"),
    ("www.electricskateboard.blog", "Electric Skateboard Blog"),
    ("www.classiccars.forum", "Classic Cars Forum"),
    ("www.mushroomforager.net", "Mushroom Forager"),
    ("www.raisedraisedgarden.com", "Raised Garden Beds"),
    ("www.spicerackrecipes.com", "Spice Rack Recipes"),
    ("www.birdwatcherlog.com", "Birdwatcher Log"),
    ("www.canoecamping.org", "Canoe Camping"),
    ("www.penpalsworld.net", "Pen Pals World"),
    ("www.mechanicalkeyboards.blog", "Mechanical Keyboards Blog"),
    ("www.terrariumbuilder.com", "Terrarium Builder"),
    ("www.knifemaking.guide", "Knife Making Guide"),
    ("www.backyardastronomy.org", "Backyard Astronomy"),
    ("www.soapcraftingdiy.com", "Soap Crafting DIY"),
    ("www.modeltrainworld.net", "Model Train World"),
    ("www.stainedglassartist.com", "Stained Glass Artist"),
    ("www.wildcampinguk.net", "Wild Camping UK"),
    ("www.geocachingtrails.com", "Geocaching Trails"),
    ("www.ceramicspottery.org", "Ceramics and Pottery"),
    ("www.antiquemapdealer.com", "Antique Map Dealer"),
    ("www.rc-planes.forum", "RC Planes Forum"),
    ("www.homebrewkombucha.com", "Homebrew Kombucha"),
    ("www.bookbindingcraft.net", "Bookbinding Craft"),
    ("www.calligraphyink.com", "Calligraphy Ink"),
    ("www.fossildigs.org", "Fossil Digs"),
    ("www.permaculturefarm.net", "Permaculture Farm"),
    ("www.tapestryweaving.com", "Tapestry Weaving"),
    ("www.chessopening.guide", "Chess Opening Guide"),
    ("www.cornholeleague.com", "Cornhole League"),
    ("www.pickleball-tips.com", "Pickleball Tips"),
    ("www.discgolfreview.com", "Disc Golf Review"),
    ("www.unicyclist.community", "Unicyclist Community"),
    ("www.slacklinetricks.com", "Slackline Tricks"),
    ("www.arrowheadhunter.net", "Arrowhead Hunter"),
    ("www.whittlingprojects.com", "Whittling Projects"),
    ("www.rocktumbling.guide", "Rock Tumbling Guide"),
    ("www.coldprocesssoap.net", "Cold Process Soap"),
    ("www.naturaldyeing.org", "Natural Dyeing"),
    ("www.pressedflowerart.com", "Pressed Flower Art"),
    ("www.charcuterieboard.blog", "Charcuterie Board Blog"),
    ("www.shrimpkeeper.com", "Shrimp Keeper"),
    ("www.reeftankdaily.com", "Reef Tank Daily"),
    ("www.guppybreeder.net", "Guppy Breeder"),
    ("www.axolotlcare.org", "Axolotl Care"),
    ("www.tarantulaforum.com", "Tarantula Forum"),
    ("www.hedgehogowner.com", "Hedgehog Owner"),
    ("www.sugargliderguide.net", "Sugar Glider Guide"),
    ("www.rabbitcare101.com", "Rabbit Care 101"),
    ("www.hamstertips.org", "Hamster Tips"),
    ("www.ferretfanatics.com", "Ferret Fanatics"),
    ("www.pigeonracingclub.net", "Pigeon Racing Club"),
    ("www.falconrynews.com", "Falconry News"),
    ("www.goatkeeperguide.com", "Goat Keeper Guide"),
    ("www.alpacafarmlife.com", "Alpaca Farm Life"),
    ("www.miniaturehorses.net", "Miniature Horses"),
    ("www.raisingducks.org", "Raising Ducks"),
    ("www.turkeyfarming.com", "Turkey Farming"),
    # Regional / international niche
    ("www.tokyonighteats.com", "Tokyo Night Eats"),
    ("www.berlinstreetfood.blog", "Berlin Street Food"),
    ("www.lisbonlocalguide.com", "Lisbon Local Guide"),
    ("www.melbournecoffee.blog", "Melbourne Coffee Blog"),
    ("www.bangkokbudgettravel.com", "Bangkok Budget Travel"),
    ("www.istanbulbazaarguide.com", "Istanbul Bazaar Guide"),
    ("www.capetownhikes.com", "Cape Town Hikes"),
    ("www.scottishhighlandswalks.net", "Scottish Highlands Walks"),
    ("www.amalficoastguide.com", "Amalfi Coast Guide"),
    ("www.norwegianfjords.blog", "Norwegian Fjords Blog"),
    ("www.patagoniatrekking.com", "Patagonia Trekking"),
    ("www.newzealandvanlife.net", "New Zealand Van Life"),
    ("www.icelandhotsprings.com", "Iceland Hot Springs"),
    ("www.provence-markets.com", "Provence Markets"),
    ("www.oaxacafoodtours.com", "Oaxaca Food Tours"),
    ("www.kyototemples.guide", "Kyoto Temples Guide"),
    ("www.saharadeserttours.com", "Sahara Desert Tours"),
    ("www.balibicycletours.com", "Bali Bicycle Tours"),
    ("www.perutrailguide.com", "Peru Trail Guide"),
    ("www.jordanpetravisitor.com", "Jordan Petra Visitor"),
    # Miscellaneous long-tail
    ("www.genealogytips.net", "Genealogy Tips"),
    ("www.penandinkdrawing.com", "Pen and Ink Drawing"),
    ("www.acrylicpouringart.com", "Acrylic Pouring Art"),
    ("www.digitalnomadlife.blog", "Digital Nomad Life"),
    ("www.freelancewritingtips.com", "Freelance Writing Tips"),
    ("www.podcastgearguide.com", "Podcast Gear Guide"),
    ("www.homerecordingstudio.net", "Home Recording Studio"),
    ("www.boardgamedesigner.com", "Board Game Designer"),
    ("www.dungeonmastertools.com", "Dungeon Master Tools"),
    ("www.paintballstrategy.net", "Paintball Strategy"),
    ("www.airsoftloadout.com", "Airsoft Loadout"),
    ("www.escaperoomreviews.com", "Escape Room Reviews"),
    ("www.puzzlecollector.net", "Puzzle Collector"),
    ("www.origamipatterns.org", "Origami Patterns"),
    ("www.speedcubing.guide", "Speedcubing Guide"),
    ("www.juggling101.com", "Juggling 101"),
    ("www.yoyotricks.net", "Yo-Yo Tricks"),
    ("www.kiteflyer.blog", "Kite Flyer Blog"),
    ("www.marblecollecting.com", "Marble Collecting"),
    ("www.stampforum.org", "Stamp Collecting Forum"),
    ("www.coincollecting.guide", "Coin Collecting Guide"),
    ("www.sportscardtrader.com", "Sports Card Trader"),
    ("www.comicbookinvestor.net", "Comic Book Investor"),
    ("www.actionfigurecollector.com", "Action Figure Collector"),
    ("www.vintagetoysforum.net", "Vintage Toys Forum"),
    ("www.trainspotterlog.com", "Trainspotter Log"),
    ("www.planespotting.blog", "Planespotting Blog"),
    ("www.lighthousevisitor.com", "Lighthouse Visitor"),
    ("www.bridgeclub.forum", "Bridge Club Forum"),
    ("www.cribbagetips.com", "Cribbage Tips"),
    ("www.mahjongstrategy.net", "Mahjong Strategy"),
    ("www.dartleague.org", "Dart League"),
    ("www.bowlingalleyreviews.com", "Bowling Alley Reviews"),
    ("www.minigolfguide.com", "Mini Golf Guide"),
    ("www.arcadecollector.net", "Arcade Collector"),
    ("www.pinballrestorations.com", "Pinball Restorations"),
    ("www.jukeboxrepair.org", "Jukebox Repair"),
    ("www.neonlightcraft.com", "Neon Light Craft"),
    ("www.typewriterclub.net", "Typewriter Club"),
    ("www.fountainpenink.blog", "Fountain Pen Ink Blog"),
    ("www.journalingprompts.com", "Journaling Prompts"),
    ("www.bulletjournal.guide", "Bullet Journal Guide"),
    ("www.planneraddict.com", "Planner Addict"),
    ("www.waxsealcraft.com", "Wax Seal Craft"),
    ("www.letterpressprint.org", "Letterpress Print"),
    ("www.screenprinting101.com", "Screen Printing 101"),
    ("www.linocutartist.net", "Linocut Artist"),
    ("www.woodblockprint.com", "Woodblock Print"),
    ("www.etchingpress.org", "Etching Press"),
    ("www.cyanotype.guide", "Cyanotype Guide"),
    ("www.filmphotographyblog.com", "Film Photography Blog"),
    ("www.darkroomtips.net", "Darkroom Tips"),
    ("www.pinholecamera.org", "Pinhole Camera"),
    ("www.lomographyfans.com", "Lomography Fans"),
    ("www.instantfilmclub.net", "Instant Film Club"),
    ("www.travelsketchbook.com", "Travel Sketchbook"),
    ("www.urbansketchersclub.org", "Urban Sketchers Club"),
    ("www.pleinairpainting.blog", "Plein Air Painting"),
    ("www.watercolorweekly.com", "Watercolor Weekly"),
    ("www.gouachepainting.net", "Gouache Painting"),
    ("www.pastelarttips.com", "Pastel Art Tips"),
    ("www.charcoaldrawing.guide", "Charcoal Drawing Guide"),
]

_N = len(WEBSITES)
_RAW_WEIGHTS: list[float] = [1.0 / (r ** 0.8) for r in range(1, _N + 1)]
_TOTAL: float = sum(_RAW_WEIGHTS)
_CUM_WEIGHTS: list[float] = []
_running = 0.0
for _w in _RAW_WEIGHTS:
    _running += _w / _TOTAL
    _CUM_WEIGHTS.append(_running)
_CUM_WEIGHTS[-1] = 1.0


def pick_website(rng: random.Random) -> tuple[str, str]:
    u = rng.random()
    idx = bisect.bisect_left(_CUM_WEIGHTS, u)
    return WEBSITES[idx]
